- name: build boxfuse
  hosts: builder
  become: yes

  tasks:


    - name: Ensure maven-package is present
      apt:
        name: maven
        state: present
    - name: Ensure project is present
      copy:
        src: /home/boxfuse-sample-java-war-hello/
        dest: /root

    - name: Ensure maven service is started
      shell: "mvn clean package"
    - name: Ensure project is packaged
      shell: "ls /root/target"
    - name: Create a tar.gz archive of a single file.
      archive:
        path: /root/target/hello-1.0.war
        dest: /root/target/hello-1.0.war.tar.gz
        format: gz



- name: run boxfuse
  hosts: runner
  become: yes

  tasks:

    - name: Ensure tomcat package is present
      apt:
        name: tomcat9
        state: present

    - name: Synchronization using rsync protocol (pull)
      command: "rsync -avz root@62.84.118.240:/root/target/hello-1.0.war /tmp"


    - name: Ensure tomcat service is started
      service:
        name: tomcat9
        state: started
