- name: build boxfuse
  hosts: builder
  become: yes

  tasks:


    - name: Ensure maven-package is present
      apt:
        name: maven
        state: present
    - name: Ensure project is present
      copy:
        src: /home/boxfuse-sample-java-war-hello/
        dest: /root

    - name: Ensure maven service is started
      shell: "mvn clean package"
    - name: Ensure project is packaged
      shell: "ls /root/target"



- name: run boxfuse
  hosts: runner
  become: yes

  tasks:

    - name: Ensure tomcat package is present
      apt:
        name: tomcat9
        state: present

    - name: Synchronization using rsync protocol (pull)
      synchronize:
        mode: pull
        src: rsync://root@62.84.118.240:"'/root/target/hello-1.0.war'"
        dest: /var/lib/tomcat9/webapps/
        use_ssh_args: yes
        compress: yes
      delegate_to: "{{inventory_hostname}}"


    - name: Ensure tomcat service is started
      service:
        name: tomcat
        state: started
