- name: build boxfuse
  hosts: builder
  become: yes

  tasks:
    - name: Add Oracle Java PPA
      apt_repository:
        repo: ppa:webupd8team/java
        state: present

    - name: Install Java 8
      apt:
        name: oracle-java8-installer
        update_cache: yes
    - name: Ensure maven-package is present
      apt:
        name: maven
        state: present
    - name: Ensure project is present
      copy:
        src: /home/ser1/boxfuse-sample-java-war-hello/
        dest: /root

    - name: Ensure maven service is started
      shell: "mvn clean package"
    - name: Ensure project is packaged
      shell: "ls /data"

- name: run boxfuse
  hosts: runner
  become: yes

  tasks:

    - name: Ensure tomcat package is present
      apt:
        name: tomcat
        state: present
    - name: Ensure project is present
      copy:
        src: ./target/hello-1.0.war
        dest: /usr/local/tomcat/webapps/
    - name: Ensure tomcat service is started
      service:
        name: tomcat
        state: started
