- name: build boxfuse
  hosts: builder
  become: yes

  tasks:


    - name: Ensure maven-package is present
      apt:
        name: maven
        state: present
    - name: Ensure project is present
      copy:
        src: /home/boxfuse-sample-java-war-hello/
        dest: /root

    - name: Ensure maven service is started
      shell: "mvn clean package"
    - name: Ensure project is packaged
      shell: "ls /root"

- name: run boxfuse
  hosts: runner
  become: yes

  tasks:

    - name: Ensure tomcat package is present
      apt:
        name: tomcat9
        state: present
    - name: Ensure project is present
      copy:
        src: /root/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /usr/local/tomcat/webapps/
    - name: Ensure tomcat service is started
      service:
        name: tomcat
        state: started
