version: '3'
services:
  builder:
    container_name: mavenop
    build:

      dockerfile: Dockerfile
    ports:
      - "8087:8080"
    links:
      - runner

  runner:
    container_name: tomcatop
    build:

      dockerfile: Dockerfile
    ports:
      - "8086:8080"







