version: '3'
services:
  builder:
    container_name: maven2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: appdata
        target: /appdata
    command: cp /home/svetlershova/boxfuse-sample-java-war-hello/target/hello-1.0.war /appdata
    links:
      - runner

  runner:
    container_name: tomcat2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - /appdata:/usr/local/tomcat/webapps/
volumes:
  appdata:






