version: '3'
services:
  builder:
    container_name: maven5
    build:
      - dockerfile: Dockerfile
    ports:
      - "8087:8080"
    links:
      - runner

  runner:
    container_name: tomcat5
    image: tomcat:9.0.53-jre11-openjdk
    build:
      - dockerfile: Dockerfile
    ports:
      - "8086:8080"







