version: '3'
services:
  builder:
    container_name: maven
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: data
        target: /data
    command: cp /home/svetlershova/boxfuse-sample-java-war-hello/target/hello-1.0.war /data
    links:
      - runner

  runner:
    container_name: tomcat
    build:
      context: .
      dockerfile: Dockerfile_2
    ports:
      - "8081:8080"
    volumes:
      - data:/usr/local/tomcat/webapps/
volumes:
  data:






