version: '3'
services:
  maven:
    container_name: maven-container2
    build:
      context: .
      dockerfile: Dockerfile

  tomcat:
    container_name: tomcat-container2
    build:
      context: .
      dockerfile: Dockerfile_2
    links:
      - "maven"
    ports:
      - "8086:8080"
