version: '3'
services:
  builder:
    container_name: maven
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/data/

  runner:
    container_name: tomcat
    build:
      context: .
      dockerfile: Dockerfile_2
    ports:
      - "8081:8080"
    volumes:
      - ./data:/usr/local/tomcat/webapps/
    depends on:
      - builder





