version: '3'
services:
  builder:
    container_name: maven
    image: maven:3.6.0-jdk-11
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/data
    links:
      - runner
    ports:
      - "8094:8080"

  runner:
    container_name: tomcat
    image: tomcat:9.0-alpine
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data:/usr/local/tomcat/webapps
    ports:
      - "8034:8080"








