---
version: '3'
services:
  builder:
    container_name: maven-container1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/data/
    links:
      - tomcat

  runner:
    container_name: tomcat-container1
    build:
      context: .
      dockerfile: Dockerfile_2
    ports:
      - "8080:8080"
    volumes:
      - ./data:/usr/local/tomcat/webapps/
    depends_on:
      - builder
___




