version: '3'
services:
  builder:
    container_name: maven3
    build:
      context: .
      dockerfile: Dockerfile

    links:
      - runner

  runner:
    container_name: tomcat3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8080"







