FROM tomcat:9.0.53-jre8-openjdk-slim-bullseye
WORKDIR /usr/local/tomcat/webapps
COPY --from=maven_builder /tmp/target/hello-1.0.war /usr/local/tomcat/webapps/hello-1.0.war
EXPOSE 8080
CMD ["catalina.sh", "run"]

