version: '3'
services:
  maven:
    container_name: maven-container3
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - tomcat
    volumes:
      - /tmp/target/hello-1.0.war


  tomcat:
    container_name: tomcat-container3
    build:
      context: .
      dockerfile: Dockerfile_2
    volumes:
      - /usr/local/tomcat/webapps/hello-1.0.war
    ports:
      - "8088:8080"



