version: '3'
services:
  builder:
    container_name: maven
    image: maven:3.6.0-jdk-10
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - runner
    ports:
      - "9000:8080"

  runner:
    container_name: tomcat
    image: tomcat:9.0-alpine
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - "8030:8080"








