version: '3'
services:
  builder:
    container_name: maven
    image: maven:3.6.0-jdk-11
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/data
    links:
      - runner

  runner:
    container_name: tomcat
    image: tomcat:8.5.3-jre8-alpine
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data:/usr/local/tomcat/webapps
    ports:
      - "8024:8080"








