version: '3'
services:
  maven:
    container_name: maven-container2
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - tomcat
    volumes:
      - /tmp/target/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war:ro


  tomcat:
    container_name: tomcat-container2
    build:
      context: .
      dockerfile: Dockerfile_2
    volumes_from:
      - /tmp/target/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war:rw
    ports:
      - "8087:8080"

