version: '3'
services:
  builder:
    container_name: maven55
    image: maven:3.6.0-jdk-11
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/local/tomcat/target
    ports:
      - "8087:8080"
    links:
      - runner

  runner:
    container_name: tomcat55
    image: tomcat:9.0.53-jre11-openjdk
    volumes:
      - ./:/usr/local/tomcat/webapps
    ports:
      - "8090:8080"








