version: '3'
services:
  builder:
    container_name: maven5
    image: maven:3.6.0-jdk-11
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8087:8080"
    links:
      - runner

  runner:
    container_name: tomcat5
    image: tomcat:9.0.53-jre11-openjdk
    build:
      context: /usr/local/tomcat/webapps/
      dockerfile: Dockerfile
    ports:
      - "8086:8080"







